freebsd_instance:
  image: freebsd-12-0-release-amd64

task:
  name: FreeBSD 12.0
  setup_script:
    - pkg install -y curl
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh -y
    - . $HOME/.cargo/env
    - rustup target add i686-unknown-freebsd
  cargo_cache:
    folder: $HOME/.cargo/registry
  test_script:
    - . $HOME/.cargo/env
    - cargo test --all --no-fail-fast
    - cargo doc --all
  i686_test_script:
    - . $HOME/.cargo/env
    - cargo test --all --exclude tokio-tls --no-fail-fast --target i686-unknown-freebsd
  before_cache_script:
    - rm -rf $HOME/.cargo/registry/index
