jobs:
- job: test_minimum
  displayName: Test Minimum
  strategy:
    matrix:
      "(Ubuntu 16.04)":
        vmImage: ubuntu-16.04
      "(Ubuntu 18.04)":
        vmImage: ubuntu-18.04
      "(macOS X Mojave)":
        vmImage: macOS-10.14
      "(macOS X Catalina)":
        vmImage: macOS-10.15
      "(Windows Server 2016)":
        vmImage: vs2017-win2016
      "(Windows Server 2019)":
        vmImage: windows-2019
  pool:
    vmImage: $(vmImage)

  steps:
  - template: azure-install-rust.yml
    parameters:
      rust_version: 1.36.0
  - script: cargo test
    displayName: cargo test
