jobs:
- job: test_quanta_nightly
  displayName: Test Quanta Nightly
  strategy:
    matrix:
      Linux:
        vmImage: ubuntu-16.04
      MacOS:
        vmImage: macOS-10.13
      Windows:
        vmImage: vs2017-win2016
  pool:
    vmImage: $(vmImage)

  steps:
  - template: azure-install-rust.yml
    parameters:
      rust_version: nightly
  - script: cargo test --features asm
    displayName: cargo test --features asm
  - script: cargo bench
    displayName: cargo bench
  - script: cargo bench --features asm
    displayName: cargo bench --features asm

