jobs:
- job: bench_stable
  displayName: Bench Stable
  strategy:
    matrix:
      "(Ubuntu 18.04)":
        vmImage: ubuntu-18.04
      "(macOS X Catalina)":
        vmImage: macOS-10.15
      "(Windows Server 2019)":
        vmImage: windows-2019
  pool:
    vmImage: $(vmImage)

  steps:
  - template: azure-install-rust.yml
    parameters:
      rust_version: stable
  - script: cargo bench
    displayName: cargo bench
